services:
  node:
    image: node:12
    stdin_open: true # docker run -i
    volumes:
      - .:/app
    tty: true # docker run -t
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - .:/app
